services:
  postgres:
    image: postgres:16-alpine
    container_name: switchpay-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: switch_pay
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: switchpay-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: