// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { env } from "./src/config/env";
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

dotenv.config();

console.log("🔄️Database Url : ", env.DATABASE_URL);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env.DATABASE_URL,
  },
});
