import { ErrorCode } from "./error-codes";
import { HttpStatus } from "./http-status";

export interface ErrorMapping {
  code: ErrorCode;
  status: HttpStatus;
  message: string;
  shouldLog: boolean;
  shouldRetry: boolean;
}

export const ErrorCodeMapping: Record<ErrorCode, ErrorMapping> = {
  // Authentication Errors
  [ErrorCode.AUTH_INVALID_CREDENTIALS]: {
    code: ErrorCode.AUTH_INVALID_CREDENTIALS,
    status: HttpStatus.UNAUTHORIZED,
    message: "Invalid email or password",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.AUTH_TOKEN_EXPIRED]: {
    code: ErrorCode.AUTH_TOKEN_EXPIRED,
    status: HttpStatus.UNAUTHORIZED,
    message: "Authentication token has expired",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.AUTH_TOKEN_INVALID]: {
    code: ErrorCode.AUTH_TOKEN_INVALID,
    status: HttpStatus.UNAUTHORIZED,
    message: "Invalid authentication token",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.AUTH_SESSION_EXPIRED]: {
    code: ErrorCode.AUTH_SESSION_EXPIRED,
    status: HttpStatus.UNAUTHORIZED,
    message: "Session has expired",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.AUTH_SESSION_INVALID]: {
    code: ErrorCode.AUTH_SESSION_INVALID,
    status: HttpStatus.UNAUTHORIZED,
    message: "Invalid session",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.AUTH_UNAUTHORIZED]: {
    code: ErrorCode.AUTH_UNAUTHORIZED,
    status: HttpStatus.UNAUTHORIZED,
    message: "Authentication required",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.AUTH_FORBIDDEN]: {
    code: ErrorCode.AUTH_FORBIDDEN,
    status: HttpStatus.FORBIDDEN,
    message: "You do not have permission to perform this action",
    shouldLog: true,
    shouldRetry: false,
  },
  [ErrorCode.AUTH_EMAIL_TAKEN]: {
    code: ErrorCode.AUTH_EMAIL_TAKEN,
    status: HttpStatus.CONFLICT,
    message: "Email address is already registered",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.AUTH_WEAK_PASSWORD]: {
    code: ErrorCode.AUTH_WEAK_PASSWORD,
    status: HttpStatus.BAD_REQUEST,
    message: "Password does not meet security requirements",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.AUTH_OAUTH_FAILED]: {
    code: ErrorCode.AUTH_OAUTH_FAILED,
    status: HttpStatus.BAD_REQUEST,
    message: "OAuth authentication failed",
    shouldLog: true,
    shouldRetry: true,
  },
  [ErrorCode.AUTH_ACCOUNT_LOCKED]: {
    code: ErrorCode.AUTH_ACCOUNT_LOCKED,
    status: HttpStatus.FORBIDDEN,
    message: "Account has been locked due to suspicious activity",
    shouldLog: true,
    shouldRetry: false,
  },
  [ErrorCode.AUTH_ACCOUNT_DISABLED]: {
    code: ErrorCode.AUTH_ACCOUNT_DISABLED,
    status: HttpStatus.FORBIDDEN,
    message: "Account has been disabled",
    shouldLog: true,
    shouldRetry: false,
  },
  [ErrorCode.AUTH_MFA_REQUIRED]: {
    code: ErrorCode.AUTH_MFA_REQUIRED,
    status: HttpStatus.UNAUTHORIZED,
    message: "Multi-factor authentication required",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.AUTH_MFA_INVALID]: {
    code: ErrorCode.AUTH_MFA_INVALID,
    status: HttpStatus.UNAUTHORIZED,
    message: "Invalid multi-factor authentication code",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.AUTH_PASSWORD_RESET_REQUIRED]: {
    code: ErrorCode.AUTH_PASSWORD_RESET_REQUIRED,
    status: HttpStatus.UNAUTHORIZED,
    message: "Password reset required",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.AUTH_EMAIL_NOT_VERIFIED]: {
    code: ErrorCode.AUTH_EMAIL_NOT_VERIFIED,
    status: HttpStatus.UNAUTHORIZED,
    message: "Email address not verified",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.AUTH_RATE_LIMITED]: {
    code: ErrorCode.AUTH_RATE_LIMITED,
    status: HttpStatus.TOO_MANY_REQUESTS,
    message: "Too many authentication attempts, please try again later",
    shouldLog: false,
    shouldRetry: true,
  },

  // Validation Errors
  [ErrorCode.VAL_INVALID_EMAIL]: {
    code: ErrorCode.VAL_INVALID_EMAIL,
    status: HttpStatus.BAD_REQUEST,
    message: "Invalid email address format",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.VAL_INVALID_PASSWORD]: {
    code: ErrorCode.VAL_INVALID_PASSWORD,
    status: HttpStatus.BAD_REQUEST,
    message: "Password does not meet complexity requirements",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.VAL_INVALID_PHONE]: {
    code: ErrorCode.VAL_INVALID_PHONE,
    status: HttpStatus.BAD_REQUEST,
    message: "Invalid phone number format",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.VAL_INVALID_CURRENCY]: {
    code: ErrorCode.VAL_INVALID_CURRENCY,
    status: HttpStatus.BAD_REQUEST,
    message: "Invalid currency code",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.VAL_INVALID_AMOUNT]: {
    code: ErrorCode.VAL_INVALID_AMOUNT,
    status: HttpStatus.BAD_REQUEST,
    message: "Invalid amount value",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.VAL_MISSING_FIELD]: {
    code: ErrorCode.VAL_MISSING_FIELD,
    status: HttpStatus.BAD_REQUEST,
    message: "Required field is missing",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.VAL_INVALID_FORMAT]: {
    code: ErrorCode.VAL_INVALID_FORMAT,
    status: HttpStatus.BAD_REQUEST,
    message: "Invalid data format",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.VAL_INVALID_ENUM]: {
    code: ErrorCode.VAL_INVALID_ENUM,
    status: HttpStatus.BAD_REQUEST,
    message: "Invalid value for enum field",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.VAL_INVALID_DATE]: {
    code: ErrorCode.VAL_INVALID_DATE,
    status: HttpStatus.BAD_REQUEST,
    message: "Invalid date format",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.VAL_INVALID_URL]: {
    code: ErrorCode.VAL_INVALID_URL,
    status: HttpStatus.BAD_REQUEST,
    message: "Invalid URL format",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.VAL_INVALID_UUID]: {
    code: ErrorCode.VAL_INVALID_UUID,
    status: HttpStatus.BAD_REQUEST,
    message: "Invalid UUID format",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.VAL_INPUT_TOO_LONG]: {
    code: ErrorCode.VAL_INPUT_TOO_LONG,
    status: HttpStatus.BAD_REQUEST,
    message: "Input exceeds maximum length",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.VAL_INPUT_TOO_SHORT]: {
    code: ErrorCode.VAL_INPUT_TOO_SHORT,
    status: HttpStatus.BAD_REQUEST,
    message: "Input is below minimum length",
    shouldLog: false,
    shouldRetry: false,
  },

  // Resource Errors
  [ErrorCode.RES_NOT_FOUND]: {
    code: ErrorCode.RES_NOT_FOUND,
    status: HttpStatus.NOT_FOUND,
    message: "Resource not found",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.RES_ALREADY_EXISTS]: {
    code: ErrorCode.RES_ALREADY_EXISTS,
    status: HttpStatus.CONFLICT,
    message: "Resource already exists",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.RES_DUPLICATE]: {
    code: ErrorCode.RES_DUPLICATE,
    status: HttpStatus.CONFLICT,
    message: "Duplicate resource",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.RES_CONFLICT]: {
    code: ErrorCode.RES_CONFLICT,
    status: HttpStatus.CONFLICT,
    message: "Resource conflict",
    shouldLog: true,
    shouldRetry: false,
  },
  [ErrorCode.RES_DELETED]: {
    code: ErrorCode.RES_DELETED,
    status: HttpStatus.GONE,
    message: "Resource has been deleted",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.RES_EXPIRED]: {
    code: ErrorCode.RES_EXPIRED,
    status: HttpStatus.GONE,
    message: "Resource has expired",
    shouldLog: false,
    shouldRetry: false,
  },

  // Database Errors
  [ErrorCode.DB_CONNECTION_FAILED]: {
    code: ErrorCode.DB_CONNECTION_FAILED,
    status: HttpStatus.INTERNAL_SERVER_ERROR,
    message: "Database connection failed",
    shouldLog: true,
    shouldRetry: true,
  },
  [ErrorCode.DB_QUERY_FAILED]: {
    code: ErrorCode.DB_QUERY_FAILED,
    status: HttpStatus.INTERNAL_SERVER_ERROR,
    message: "Database query failed",
    shouldLog: true,
    shouldRetry: false,
  },
  [ErrorCode.DB_TRANSACTION_FAILED]: {
    code: ErrorCode.DB_TRANSACTION_FAILED,
    status: HttpStatus.INTERNAL_SERVER_ERROR,
    message: "Database transaction failed",
    shouldLog: true,
    shouldRetry: true,
  },
  [ErrorCode.DB_CONSTRAINT_VIOLATION]: {
    code: ErrorCode.DB_CONSTRAINT_VIOLATION,
    status: HttpStatus.CONFLICT,
    message: "Database constraint violation",
    shouldLog: true,
    shouldRetry: false,
  },
  [ErrorCode.DB_UNIQUE_VIOLATION]: {
    code: ErrorCode.DB_UNIQUE_VIOLATION,
    status: HttpStatus.CONFLICT,
    message: "Unique constraint violation",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.DB_FOREIGN_KEY_VIOLATION]: {
    code: ErrorCode.DB_FOREIGN_KEY_VIOLATION,
    status: HttpStatus.CONFLICT,
    message: "Foreign key constraint violation",
    shouldLog: true,
    shouldRetry: false,
  },
  [ErrorCode.DB_TIMEOUT]: {
    code: ErrorCode.DB_TIMEOUT,
    status: HttpStatus.REQUEST_TIMEOUT,
    message: "Database operation timed out",
    shouldLog: true,
    shouldRetry: true,
  },
  [ErrorCode.DB_POOL_EXHAUSTED]: {
    code: ErrorCode.DB_POOL_EXHAUSTED,
    status: HttpStatus.SERVICE_UNAVAILABLE,
    message: "Database connection pool exhausted",
    shouldLog: true,
    shouldRetry: true,
  },

  // Payment Errors
  [ErrorCode.PAY_INSUFFICIENT_FUNDS]: {
    code: ErrorCode.PAY_INSUFFICIENT_FUNDS,
    status: HttpStatus.PAYMENT_REQUIRED,
    message: "Insufficient funds",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.PAY_PROVIDER_ERROR]: {
    code: ErrorCode.PAY_PROVIDER_ERROR,
    status: HttpStatus.BAD_GATEWAY,
    message: "Payment provider error",
    shouldLog: true,
    shouldRetry: true,
  },
  [ErrorCode.PAY_PROVIDER_TIMEOUT]: {
    code: ErrorCode.PAY_PROVIDER_TIMEOUT,
    status: HttpStatus.GATEWAY_TIMEOUT,
    message: "Payment provider timeout",
    shouldLog: true,
    shouldRetry: true,
  },
  [ErrorCode.PAY_INVALID_REFERENCE]: {
    code: ErrorCode.PAY_INVALID_REFERENCE,
    status: HttpStatus.BAD_REQUEST,
    message: "Invalid payment reference",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.PAY_DUPLICATE_REFERENCE]: {
    code: ErrorCode.PAY_DUPLICATE_REFERENCE,
    status: HttpStatus.CONFLICT,
    message: "Duplicate payment reference",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.PAY_SETTLEMENT_FAILED]: {
    code: ErrorCode.PAY_SETTLEMENT_FAILED,
    status: HttpStatus.INTERNAL_SERVER_ERROR,
    message: "Payment settlement failed",
    shouldLog: true,
    shouldRetry: true,
  },
  [ErrorCode.PAY_REFUND_FAILED]: {
    code: ErrorCode.PAY_REFUND_FAILED,
    status: HttpStatus.INTERNAL_SERVER_ERROR,
    message: "Payment refund failed",
    shouldLog: true,
    shouldRetry: true,
  },
  [ErrorCode.PAY_WEBHOOK_VERIFICATION_FAILED]: {
    code: ErrorCode.PAY_WEBHOOK_VERIFICATION_FAILED,
    status: HttpStatus.BAD_REQUEST,
    message: "Webhook signature verification failed",
    shouldLog: true,
    shouldRetry: false,
  },
  [ErrorCode.PAY_TRANSITION_INVALID]: {
    code: ErrorCode.PAY_TRANSITION_INVALID,
    status: HttpStatus.BAD_REQUEST,
    message: "Invalid payment state transition",
    shouldLog: true,
    shouldRetry: false,
  },

  // Provider Errors
  [ErrorCode.PROV_CREDENTIAL_INVALID]: {
    code: ErrorCode.PROV_CREDENTIAL_INVALID,
    status: HttpStatus.UNAUTHORIZED,
    message: "Provider credentials are invalid",
    shouldLog: true,
    shouldRetry: false,
  },
  [ErrorCode.PROV_CREDENTIAL_EXPIRED]: {
    code: ErrorCode.PROV_CREDENTIAL_EXPIRED,
    status: HttpStatus.UNAUTHORIZED,
    message: "Provider credentials have expired",
    shouldLog: true,
    shouldRetry: false,
  },
  [ErrorCode.PROV_UNSUPPORTED]: {
    code: ErrorCode.PROV_UNSUPPORTED,
    status: HttpStatus.BAD_REQUEST,
    message: "Unsupported provider",
    shouldLog: false,
    shouldRetry: false,
  },
  [ErrorCode.PROV_CIRCUIT_OPEN]: {
    code: ErrorCode.PROV_CIRCUIT_OPEN,
    status: HttpStatus.SERVICE_UNAVAILABLE,
    message: "Provider circuit breaker is open",
    shouldLog: true,
    shouldRetry: true,
  },
  [ErrorCode.PROV_RATE_LIMITED]: {
    code: ErrorCode.PROV_RATE_LIMITED,
    status: HttpStatus.TOO_MANY_REQUESTS,
    message: "Provider rate limit exceeded",
    shouldLog: false,
    shouldRetry: true,
  },
  [ErrorCode.PROV_SERVICE_UNAVAILABLE]: {
    code: ErrorCode.PROV_SERVICE_UNAVAILABLE,
    status: HttpStatus.SERVICE_UNAVAILABLE,
    message: "Provider service is unavailable",
    shouldLog: true,
    shouldRetry: true,
  },
  [ErrorCode.PROV_CONFIGURATION_ERROR]: {
    code: ErrorCode.PROV_CONFIGURATION_ERROR,
    status: HttpStatus.INTERNAL_SERVER_ERROR,
    message: "Provider configuration error",
    shouldLog: true,
    shouldRetry: false,
  },

  // System Errors
  [ErrorCode.SYS_INTERNAL_ERROR]: {
    code: ErrorCode.SYS_INTERNAL_ERROR,
    status: HttpStatus.INTERNAL_SERVER_ERROR,
    message: "Internal server error",
    shouldLog: true,
    shouldRetry: false,
  },
  [ErrorCode.SYS_SERVICE_UNAVAILABLE]: {
    code: ErrorCode.SYS_SERVICE_UNAVAILABLE,
    status: HttpStatus.SERVICE_UNAVAILABLE,
    message: "Service temporarily unavailable",
    shouldLog: true,
    shouldRetry: true,
  },
  [ErrorCode.SYS_MAINTENANCE]: {
    code: ErrorCode.SYS_MAINTENANCE,
    status: HttpStatus.SERVICE_UNAVAILABLE,
    message: "System is under maintenance",
    shouldLog: true,
    shouldRetry: true,
  },
  [ErrorCode.SYS_TIMEOUT]: {
    code: ErrorCode.SYS_TIMEOUT,
    status: HttpStatus.REQUEST_TIMEOUT,
    message: "Operation timed out",
    shouldLog: true,
    shouldRetry: true,
  },
  [ErrorCode.SYS_OUT_OF_MEMORY]: {
    code: ErrorCode.SYS_OUT_OF_MEMORY,
    status: HttpStatus.INTERNAL_SERVER_ERROR,
    message: "System out of memory",
    shouldLog: true,
    shouldRetry: false,
  },
  [ErrorCode.SYS_DISK_FULL]: {
    code: ErrorCode.SYS_DISK_FULL,
    status: HttpStatus.INTERNAL_SERVER_ERROR,
    message: "System disk is full",
    shouldLog: true,
    shouldRetry: false,
  },
  [ErrorCode.SYS_CONFIGURATION_ERROR]: {
    code: ErrorCode.SYS_CONFIGURATION_ERROR,
    status: HttpStatus.INTERNAL_SERVER_ERROR,
    message: "System configuration error",
    shouldLog: true,
    shouldRetry: false,
  },

  // Business Logic Errors
  [ErrorCode.BIZ_INVALID_STATE]: {
    code: ErrorCode.BIZ_INVALID_STATE,
    status: HttpStatus.BAD_REQUEST,
    message: "Invalid business state",
    shouldLog: true,
    shouldRetry: false,
  },
  [ErrorCode.BIZ_INVALID_OPERATION]: {
    code: ErrorCode.BIZ_INVALID_OPERATION,
    status: HttpStatus.BAD_REQUEST,
    message: "Invalid operation for current state",
    shouldLog: true,
    shouldRetry: false,
  },
  [ErrorCode.BIZ_INSUFFICIENT_PERMISSIONS]: {
    code: ErrorCode.BIZ_INSUFFICIENT_PERMISSIONS,
    status: HttpStatus.FORBIDDEN,
    message: "Insufficient permissions for this operation",
    shouldLog: true,
    shouldRetry: false,
  },
  [ErrorCode.BIZ_WORKFLOW_ERROR]: {
    code: ErrorCode.BIZ_WORKFLOW_ERROR,
    status: HttpStatus.INTERNAL_SERVER_ERROR,
    message: "Workflow execution error",
    shouldLog: true,
    shouldRetry: true,
  },
  [ErrorCode.BIZ_INTEGRITY_ERROR]: {
    code: ErrorCode.BIZ_INTEGRITY_ERROR,
    status: HttpStatus.CONFLICT,
    message: "Business integrity violation",
    shouldLog: true,
    shouldRetry: false,
  },
};
