export enum ErrorCode {
  // Authentication Errors (AUTH-xxx)
  AUTH_INVALID_CREDENTIALS = "AUTH-001",
  AUTH_TOKEN_EXPIRED = "AUTH-002",
  AUTH_TOKEN_INVALID = "AUTH-003",
  AUTH_SESSION_EXPIRED = "AUTH-004",
  AUTH_SESSION_INVALID = "AUTH-005",
  AUTH_UNAUTHORIZED = "AUTH-006",
  AUTH_FORBIDDEN = "AUTH-007",
  AUTH_EMAIL_TAKEN = "AUTH-008",
  AUTH_WEAK_PASSWORD = "AUTH-009",
  AUTH_OAUTH_FAILED = "AUTH-010",
  AUTH_ACCOUNT_LOCKED = "AUTH-011",
  AUTH_ACCOUNT_DISABLED = "AUTH-012",
  AUTH_MFA_REQUIRED = "AUTH-013",
  AUTH_MFA_INVALID = "AUTH-014",
  AUTH_PASSWORD_RESET_REQUIRED = "AUTH-015",
  AUTH_EMAIL_NOT_VERIFIED = "AUTH-016",
  AUTH_RATE_LIMITED = "AUTH-017",

  // Validation Errors (VAL-xxx)
  VAL_INVALID_EMAIL = "VAL-001",
  VAL_INVALID_PASSWORD = "VAL-002",
  VAL_INVALID_PHONE = "VAL-003",
  VAL_INVALID_CURRENCY = "VAL-004",
  VAL_INVALID_AMOUNT = "VAL-005",
  VAL_MISSING_FIELD = "VAL-006",
  VAL_INVALID_FORMAT = "VAL-007",
  VAL_INVALID_ENUM = "VAL-008",
  VAL_INVALID_DATE = "VAL-009",
  VAL_INVALID_URL = "VAL-010",
  VAL_INVALID_UUID = "VAL-011",
  VAL_INPUT_TOO_LONG = "VAL-012",
  VAL_INPUT_TOO_SHORT = "VAL-013",

  // Resource Errors (RES-xxx)
  RES_NOT_FOUND = "RES-001",
  RES_ALREADY_EXISTS = "RES-002",
  RES_DUPLICATE = "RES-003",
  RES_CONFLICT = "RES-004",
  RES_DELETED = "RES-005",
  RES_EXPIRED = "RES-006",

  // Database Errors (DB-xxx)
  DB_CONNECTION_FAILED = "DB-001",
  DB_QUERY_FAILED = "DB-002",
  DB_TRANSACTION_FAILED = "DB-003",
  DB_CONSTRAINT_VIOLATION = "DB-004",
  DB_UNIQUE_VIOLATION = "DB-005",
  DB_FOREIGN_KEY_VIOLATION = "DB-006",
  DB_TIMEOUT = "DB-007",
  DB_POOL_EXHAUSTED = "DB-008",

  // Payment Errors (PAY-xxx)
  PAY_INSUFFICIENT_FUNDS = "PAY-001",
  PAY_PROVIDER_ERROR = "PAY-002",
  PAY_PROVIDER_TIMEOUT = "PAY-003",
  PAY_INVALID_REFERENCE = "PAY-004",
  PAY_DUPLICATE_REFERENCE = "PAY-005",
  PAY_SETTLEMENT_FAILED = "PAY-006",
  PAY_REFUND_FAILED = "PAY-007",
  PAY_WEBHOOK_VERIFICATION_FAILED = "PAY-008",
  PAY_TRANSITION_INVALID = "PAY-009",

  // Provider Errors (PROV-xxx)
  PROV_CREDENTIAL_INVALID = "PROV-001",
  PROV_CREDENTIAL_EXPIRED = "PROV-002",
  PROV_UNSUPPORTED = "PROV-003",
  PROV_CIRCUIT_OPEN = "PROV-004",
  PROV_RATE_LIMITED = "PROV-005",
  PROV_SERVICE_UNAVAILABLE = "PROV-006",
  PROV_CONFIGURATION_ERROR = "PROV-007",

  // System Errors (SYS-xxx)
  SYS_INTERNAL_ERROR = "SYS-001",
  SYS_SERVICE_UNAVAILABLE = "SYS-002",
  SYS_MAINTENANCE = "SYS-003",
  SYS_TIMEOUT = "SYS-004",
  SYS_OUT_OF_MEMORY = "SYS-005",
  SYS_DISK_FULL = "SYS-006",
  SYS_CONFIGURATION_ERROR = "SYS-007",

  // Business Logic Errors (BIZ-xxx)
  BIZ_INVALID_STATE = "BIZ-001",
  BIZ_INVALID_OPERATION = "BIZ-002",
  BIZ_INSUFFICIENT_PERMISSIONS = "BIZ-003",
  BIZ_WORKFLOW_ERROR = "BIZ-004",
  BIZ_INTEGRITY_ERROR = "BIZ-005",
}
